window.ALICE_RADAR_CONFIG={
  dataUrl:"./data/jobs.json",
  appVersion:"6.22",
  sync:{
    enabled:true,
    url:"https://nlhxjpartgvplythgzrz.supabase.co",
    publishableKey:"sb_publishable_uA9EbSMwJ5oFraqP-r5njg_EXtLSjEH",
    table:"job_state"
  }
};
